export const STYLE_CLASSES = {
  container: "flex h-screen bg-white dark:bg-black",
  mainContent: "flex-1 p-10 overflow-y-auto bg-white dark:bg-black",
  welcomeHeader: "text-2xl font-semibold text-[#12284b] dark:text-[#e2f4fd]",
  welcomeName: "text-4xl",
  userInfo: "flex items-center text-[#12284b] dark:text-[#e2f4fd]",
  userName: "text-2xl",
  avatar: "flex-shrink-0 rounded-full mr-4",
  statCard:
    "bg-blue-200 dark:bg-neutral-700 shadow-md rounded-lg p-6 flex items-center",
  statIcon: "text-3xl mr-4",
  statValue: "text-3xl font-bold text-[#12284b] dark:text-[#e2f4fd]",
  statLabel: "text-[#12284b] dark:dark:text-[#e2f4fd]",
  sectionTitle: "text-xl font-semibold text-[#12284b] dark:text-[#e2f4fd] mb-4",
  classroomButton: `flex items-center justify-center px-4 py-3 bg-gradient-to-r from-blue-500 to-blue-600 text-white rounded-lg shadow-md hover:from-blue-600 hover:to-blue-700 transition-all duration-300 transform hover:scale-105 focus:outline-none focus:ring-2 focus:ring-blue-400`,
  sectionCard: "bg-[#e2f4fd] dark:bg-neutral-700 shadow-md rounded-lg mb-8",
  sectionHeader: "p-6 border-b border-blue-300 dark:border-neutral-600",
  sectionHeaderTitle: "text-xl font-semibold text-blue-900 dark:text-white",
  sectionContent: "p-6",
  subjectCard:
    "flex flex-col justify-between items-start p-4 border border-blue-300 dark:border-neutral-600 rounded-lg shadow-md bg-blue-300 dark:bg-neutral-600",
  subjectName: "text-lg font-semibold text-blue-900 dark:text-white",
  subjectProgress: "text-blue-700 dark:text-gray-300",
  progressBar: "bg-blue-600 text-white text-center rounded-lg",
  progressLabel: "text-center text-xs mt-1 text-blue-700 dark:text-gray-300",
  recommendedCard: `p-4 border border-blue-300 dark:border-neutral-600 rounded-lg shadow-md bg-blue-300 dark:bg-neutral-600 transition-all duration-300 hover:scale-105`,
  recommendedTitle: "text-lg font-semibold text-blue-900 dark:text-white",
  recommendedDescription: "text-blue-700 dark:text-gray-300 mt-2",
  recommendedProgress: "text-blue-800 dark:text-blue-400 font-semibold",
} as const;
